apiVersion: v2
appVersion: 0.0.1
name: traderfour-app
version: 0.0.1
description: A helm chart for traderfour app project
home: https://gitlab.com/traderfour/app
maintainers:
- name: Alireza Josheghani
  url: https://github.com/mrjosh
sources:
- https://gitlab.com/traderfour/app
type: application
