name: "sample"
replicaCount: 1

ingressController: nginx

service:
  type: ClusterIP

domainName: "app.trader4.net"

tls:
  enabled: false
  secretName: app-trader4-net-tls
  clusterIssuer: le-clusterissuer

image:
  repository: "trader4.{{ .Values.name }}-app"
  pullPolicy: Always
  tag: latest

resources: {}
tolerations: {}
